### ISSUE TITLE
password encryption is not synchronous 

### ISSUE THREAD

**Issue by WafiqSalie** [MrKiplin/xlsx-encrypter#8]
Promise function on the encryptXlsxFile function causing a timing issue. When fetching the binary of the document the file still seems to have no encryption because of the promise methods. I managed to resolved this issue by added async and await ie:

 public **async** exportWorkSheetsToFile(
    filePath: string,
    workSheets: WorkSheetWithName[],
    password?: string
  ): **Promise**<void> {
    const workBook = this.createWorkBook();

    for (const workSheet of workSheets) {
      utils.book_append_sheet(workBook, workSheet.sheet, workSheet.name);
    }

    writeFile(workBook, filePath);

    if (password) {
      **await** this.encryptXlsxFile(filePath, password);
    }
    return;
  }

  private createWorkBook(): WorkBook {
    return utils.book_new();
  }

  private **async** encryptXlsxFile(filePath: string, password: string) {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    **await** XlsxPopulate.fromFileAsync(filePath).then(**async** (workbook: any) => {
     **await** workbook.toFileAsync(filePath, {
        password: password,
      });
    });
  }
}

**Comment by MrKiplin** [comment]
Thank you @WafiqSalie, I'll take a look at this 👍
